### PR TITLE
Fix for KeyStore DoS vulnerability

### PR DESCRIPTION
**Pull request by Shashank-In**
https://github.com/ava-labs/gecko/issues/195

### CODE REVIEW

**Comment by swdee** [comment]
Duplicating the if function is not very nice and the change also requires code comments to say why the checked password is being truncated.   Would you update the code to something like the following;

```
// As per issue https://github.com/ava-labs/gecko/issues/195 it was found the longer the length of password the slower zxcvbn.PasswordStrength() performs.  
// To avoid performance issues and DOS vector we only check the first 50 characters of the password.
checkPass := args.Password

if len(args.Password) >= 50 {
    checkPass = args.Password[:50]
}

if zxcvbn.PasswordStrength(checkPass, nil).Score < requiredPassScore {
    return errWeakPassword
}
```

**Comment by swdee** [comment]
That would overflow too, so remove `>=` and change to just `>`, ie:

```
if len(args.Password) > 50 {
    checkPass = args.Password[:50]
}
```

**Comment by Shashank-In** [comment]
Hi @swdee 
Thank you for your advice. I tested the code in local and it works perfectly. I have updated the fix.

**Comment by swdee** [comment]
Almost there, the last thing needed is for the code changes to be run through `go fmt` to fix code alignment and formatting.  See https://blog.golang.org/gofmt

Once that is done, it looks good from my eyes.  Thanks for your testing an contribution.

**Comment by Shashank-In** [comment]
@swdee Fix it. Thanks again

**Pull request merged**
