### PR TITLE
go mod support

### PR DESCRIPTION
**Pull request by adasari**
Hi Team,

Converted current gecko project to use go modules. I used 1.13 as go version at the moment (i saw somewhere that gecko is using 1.13 only)

I suppose this would fix https://github.com/ava-labs/gecko/issues/21

All current unit tests looks good and able to generate ava binary as well. 

Please take a look. Thanks.

### CODE REVIEW

**Comment by adasari** [comment]
The current code is working  with 1.14 without any dependencies change. 
Working => build and tests are successful.

**Comment by adasari** [comment]
pipeline is failing with following error. 
```
#13 19.66 ./scripts/build.sh: line 20: cd: /go/src/github.com/ava-labs/coreth: No such file or directory
#13 ERROR: executor failed running [/bin/sh -c ./scripts/build.sh]: runc did not terminate sucessfully
```
can some look into it ? let me know if any changes are need to address the pipeline issue. thanks.

**Comment by StephenButtolph** [comment]
@Determinant Have you had time to review this PR yet?

**Comment by Determinant** [comment]
I'll take a look and hopefully improve/merge it by the end of this week.

**Comment by adasari** [comment]
@StephenButtolph  @Determinant - fyi. generating images of vm (from coreth) should be separated from gecko build.sh. running go get in a repo would add fetched go packages into go mod even though they are not used in that repo. Also build.sh should run go mod tidy for build gecko repo. Let me know if you would like to discuss on more separating build.sh

**Comment by StephenButtolph** [comment]
@Determinant @danlaine What's the status on this?

**Comment by danlaine** [comment]
Working on improving the build process. Will probably make a PR later today or tomorrow. We can close this PR.

**Pull request closed without merging**
